# Generated by Django 5.2.6 on 2026-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0012_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='award',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
