# Generated by Django 5.2.6 on 2026-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0013_award_category_award_is_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='atg_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
