# Generated by Django 5.2.6 on 2026-07-26 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0014_donation_atg_requested_donation_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='AwardNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nominee_full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('nominee_profile_photo', models.FileField(blank=True, upload_to='award_nominations/%Y/%m/')),
                ('company_full_address', models.TextField()),
                ('award_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations', to='foundation.award')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
