# Generated by Django 5.2.6 on 2026-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0015_donation_donation_category_awardnomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
