# Generated by Django 5.2.16 on 2026-07-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0016_mediaasset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='project_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
