# Generated by Django 5.2.16 on 2026-07-27 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _impact_integer(value):
    if isinstance(value, bool):
        return 0
    if isinstance(value, (int, float)):
        return max(int(value), 0)
    if isinstance(value, str):
        digits = "".join(character for character in value if character.isdigit())
        return int(digits) if digits else 0
    return 0


def populate_project_funding(apps, schema_editor):
    Project = apps.get_model("foundation", "Project")
    Donation = apps.get_model("foundation", "Donation")
    DonationTransaction = apps.get_model("foundation", "DonationTransaction")

    projects_by_slug = {project.slug: project for project in Project.objects.all()}
    paid_statuses = {"paid", "subscription_authorized"}

    for donation in Donation.objects.all().iterator():
        project = projects_by_slug.get(donation.project_slug)
        if project:
            donation.project_id = project.id
            if donation.project_title != project.title:
                donation.project_title = project.title
                donation.save(update_fields=["project", "project_title"])
            else:
                donation.save(update_fields=["project"])

        if donation.status not in paid_statuses:
            continue

        payment_id = donation.razorpay_payment_id or f"legacy-donation-{donation.id}"
        DonationTransaction.objects.get_or_create(
            razorpay_payment_id=payment_id,
            defaults={
                "donation_id": donation.id,
                "project_id": donation.project_id,
                "amount_paise": donation.amount * 100,
                "currency": donation.currency,
                "status": "captured",
                "source": "legacy_migration",
                "paid_at": donation.verified_at or donation.created_at,
                "payload": {"migrated_from_donation_id": donation.id},
            },
        )

    for project in Project.objects.all():
        impact = project.impact_numbers if isinstance(project.impact_numbers, dict) else {}
        target = _impact_integer(
            impact.get("budget")
            or impact.get("target")
            or impact.get("allocated_budget")
        )
        previous_public_total = _impact_integer(
            impact.get("spent")
            or impact.get("raised")
            or impact.get("utilized")
            or impact.get("deployed")
        )
        actual_paise = (
            DonationTransaction.objects.filter(project_id=project.id).aggregate(
                total=models.Sum(
                    models.F("amount_paise") - models.F("refunded_amount_paise")
                )
            )["total"]
            or 0
        )
        actual_rupees = actual_paise // 100
        project.funding_target_amount = target
        project.manual_raised_amount = max(previous_public_total - actual_rupees, 0)
        project.save(
            update_fields=["funding_target_amount", "manual_raised_amount"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0017_donation_project_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='foundation.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_target_amount',
            field=models.PositiveBigIntegerField(default=0, help_text='Public fundraising target in rupees.'),
        ),
        migrations.AddField(
            model_name='project',
            name='manual_raised_amount',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Internal opening/offline balance in rupees. Use the admin funding control to update it.'),
        ),
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_payment_id', models.CharField(max_length=80, unique=True)),
                ('amount_paise', models.PositiveBigIntegerField()),
                ('refunded_amount_paise', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('captured', 'Captured'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], default='captured', max_length=24)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='foundation.donation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='foundation.project')),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.RunPython(populate_project_funding, migrations.RunPython.noop),
    ]
