# Generated by Django 5.2.16 on 2026-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0019_rename_atg_requested_to_eighty_g_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional for YouTube videos because the YouTube thumbnail is loaded automatically. Recommended for uploaded MP4 videos.', upload_to='impact-videos/thumbnails/%Y/%m/')),
                ('youtube_url', models.URLField(blank=True, help_text='Primary option. Paste a YouTube watch, Shorts, live, or youtu.be link.', max_length=500)),
                ('video_file', models.FileField(blank=True, help_text='Optional direct MP4, WebM, MOV, or M4V upload (maximum 100 MB).', upload_to='impact-videos/videos/%Y/%m/')),
                ('category', models.CharField(blank=True, max_length=120)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impact Video',
                'verbose_name_plural': 'Impact Videos',
                'ordering': ['sort_order', '-published_on', '-created_at'],
            },
        ),
    ]
